### ISSUE TITLE
Extract data from map

### ISSUE THREAD

**Issue by tonysprenk** [dugwood/isochrone-isodistance-with-google-maps#2]
Would it be possible somehow to extract data such as postal codes from the mapped area?

**Comment by dugwood** [comment]
@tonysprenk I don't think it's relevant to this project.

But you can:

- use this project to get the final polygon
- use other data (openstreetmap or the like) to determine postal codes polygons (say this location with zip 12345 is a polygon)
- try to detect if two polygons intersect a bit

For other projects I've used the logic of https://assemblysys.com/php-point-in-polygon-algorithm/ but it's not 2 polygons, it's just one point in or out the polygon.
